### ISSUE TITLE
Error of "name 'mainiconfontcolor' is not defined"

### ISSUE THREAD

**Issue by domsle** [fadeouter/argosWeather#1]
Hey,
I cannot run this script, because I get this error:

`
Traceback (most recent call last):
  File "weather.15m.py", line 735, in <module>
    checks()
  File "weather.15m.py", line 731, in checks
    print_main()
  File "weather.15m.py", line 684, in print_main
    <g transform="translate('+str(translate)+',0)">' + nextIcon +'</g>\
NameError: name 'mainiconfontcolor' is not defined
`
I am a total newbie when it comes to python. I tried running this script, but at first I got errors regarding print functions missing (). So I converted this script using 2to3. I have my api key and location adresses pasted.
Could you help me?

**Comment by fadeouter** [comment]
Hi, @domsle! Thanks for your report. There was my mistake. Now I fixed it and you can try!
