### ISSUE TITLE
Text and chart are flipped

### ISSUE THREAD

**Issue by domsle** [fadeouter/argosWeather#3]
![image](https://user-images.githubusercontent.com/18559095/34692195-9ab8ec18-f4bf-11e7-81b7-3c16872992d3.png)
 It broke very recently. I did not cause it to be broken by any modifications. Can you help me investigate it? Im clueless.

Im using latest stable Gnome on Manjaro.

**Comment by fadeouter** [comment]
It is interesting. Thanks for sharing! In order to investigate I suggest run script in terminal and post here link to output (it going to be wide, so try to use Github Gist or similar service).

**Comment by fadeouter** [comment]
It could be caused by wrong interpreting of CSS 'transform' property I guess, but it need to see output first.

**Comment by domsle** [comment]
Here you go.
[gist](https://gist.github.com/domsle/dcc34b16c59528002280977e2e5bf2ce)

**Comment by fadeouter** [comment]
Checked. For now looks absolutely normally on my Ubuntu 17.10. I'll try in Manjaro in WM.

**Comment by fadeouter** [comment]
Hi! Probably I fixed the problem. Please leave comment that everything is working fine.

**Comment by domsle** [comment]
Yes, it works perfectly! Thank you! :)
